export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_LOCATION = "ADD_LOCATION";
export const SET_CHECKBOX = "SET_CHECKBOX";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_LOCATION = "EDIT_LOCATION";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_LOCATION = "DELETE_LOCATION"
export const DRAG_MAP_MARKER = "DRAG_MAP_MARKER";